version: '3.9'

services:
  application_db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./maria_store:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=demo
      - MYSQL_USER=demo
      - MYSQL_DATABASE=sim

  template_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=demo
      - MONGO_INITDB_ROOT_PASSWORD=demo
      
  backend:
    build:
        context: backend
        dockerfile: Dockerfile
    env_file:
        /backend/.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - application_db
  migration:
    image: mariadb
    command: python manage.py migrate
    depends_on:
      - application_db
  
  frontend:
    build: 
        context: frontend
        dockerfile: Dockerfile
    env_file:
        /frontend/.env
    ports:
      - 3000:3000
    depends_on:
      - backend