# THIS IS NOT A PRODUCTION ENVIRONMENT
version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo_storage:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=demo
      - MONGO_INITDB_ROOT_PASSWORD=passdemo