version: '3.9'

services:
  application_db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./maria_store:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=demo
      - MYSQL_USER=demo
      - MYSQL_DATABASE=sim

  template_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=demo
      - MONGO_INITDB_ROOT_PASSWORD=demo